apiVersion: v1
data:
  mesh: |-
    accessLogEncoding: TEXT
    accessLogFile: ""
    accessLogFormat: ""
    defaultConfig:
      concurrency: 2
      configPath: ./etc/istio/proxy
      connectTimeout: 10s
      controlPlaneAuthPolicy: NONE
      discoveryAddress: istiod.istio-system.svc:15012
      drainDuration: 45s
      parentShutdownDuration: 1m0s
      proxyAdminPort: 15000
      proxyMetadata:
        DNS_AGENT: ""
      serviceCluster: istio-proxy
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    disableMixerHttpReports: true
    disablePolicyChecks: true
    enablePrometheusMerge: false
    ingressClass: istio
    ingressControllerMode: STRICT
    ingressService: istio-ingressgateway
    protocolDetectionTimeout: 100ms
    reportBatchMaxEntries: 100
    reportBatchMaxTime: 1s
    sdsUdsPath: unix:/etc/istio/proxy/SDS
    trustDomain: cluster.local
    trustDomainAliases: null
  meshNetworks: |-
    networks:
      xmain:
        endpoints:
        - fromRegistry: xmain
        gateways:
        - port: 443
          registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local
      xremote:
        endpoints:
        - fromRegistry: xremote
        gateways:
        - port: 443
          registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local
      xremote2:
        endpoints:
        - fromRegistry: xremote2
        gateways:
        - port: 443
          registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mesh":"accessLogEncoding: TEXT\naccessLogFile: \"\"\naccessLogFormat: \"\"\ndefaultConfig:\n  concurrency: 2\n  configPath: ./etc/istio/proxy\n  connectTimeout: 10s\n  controlPlaneAuthPolicy: NONE\n  discoveryAddress: istiod.istio-system.svc:15012\n  drainDuration: 45s\n  parentShutdownDuration: 1m0s\n  proxyAdminPort: 15000\n  proxyMetadata:\n    DNS_AGENT: \"\"\n  serviceCluster: istio-proxy\n  tracing:\n    zipkin:\n      address: zipkin.istio-system:9411\ndisableMixerHttpReports: true\ndisablePolicyChecks: true\nenablePrometheusMerge: false\ningressClass: istio\ningressControllerMode: STRICT\ningressService: istio-ingressgateway\nprotocolDetectionTimeout: 100ms\nreportBatchMaxEntries: 100\nreportBatchMaxTime: 1s\nsdsUdsPath: unix:/etc/istio/proxy/SDS\ntrustDomain: cluster.local\ntrustDomainAliases: null","meshNetworks":"networks:\n  xmain:\n    endpoints:\n    - fromRegistry: xmain\n    gateways:\n    - port: 443\n      registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local\n  xremote:\n    endpoints:\n    - fromRegistry: xremote\n    gateways:\n    - port: 443\n      registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local\n  xremote2:\n    endpoints:\n    - fromRegistry: xremote2\n    gateways:\n    - port: 443\n      registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"install.operator.istio.io/owning-resource":"installed-state","install.operator.istio.io/owning-resource-namespace":"istio-system","istio.io/rev":"default","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.6.4","release":"istio"},"name":"istio","namespace":"istio-system"}}
  creationTimestamp: "2020-08-28T07:46:53Z"
  labels:
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.4
    release: istio
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mesh: {}
        f:meshNetworks: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:install.operator.istio.io/owning-resource: {}
          f:install.operator.istio.io/owning-resource-namespace: {}
          f:istio.io/rev: {}
          f:operator.istio.io/component: {}
          f:operator.istio.io/managed: {}
          f:operator.istio.io/version: {}
          f:release: {}
    manager: istioctl
    operation: Update
    time: "2020-08-28T07:46:53Z"
  name: istio
  namespace: istio-system
  resourceVersion: "5341"
  selfLink: /api/v1/namespaces/istio-system/configmaps/istio
  uid: 93db4e97-4fee-4190-9fe8-398d8e94d592
