apiVersion: v1
data:
  secretkey: eGIwd3pQQnVaTkZPQUVEdEZIMU4wbU9paFNqNlJvMDBOZkpndVQ1aFVQQVQvZVcxQUNwR2FYckFhUkl0cXpaOQpEUEYzTi85L3E3eStrSW0vaEM2bHY0VFZRNnNxZ08wWHBqbGJzd0dJOUNTZE5oYUlNeFR1YW1GVjg2eUpTMHhRCmQyVVpWVVVzdnZ6K2FEZVpEUjBmUUR5Nk9nNlFDY1lNTHF1dmJsWisrc1E9
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
type: Opaque
