apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: "2020-07-23T09:16:07Z"
  generateName: calico-node-
  labels:
    controller-revision-hash: 67d875c67
    k8s-app: calico-node
    pod-template-generation: "1"
  name: calico-node-drcrq
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: calico-node
    uid: 4083172e-f451-49d0-b314-bf77a3332e51
  resourceVersion: "861"
  selfLink: /api/v1/namespaces/kube-system/pods/calico-node-drcrq
  uid: e197315b-6bcc-42cb-ad60-30c3c4e29411
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - master01
  containers:
  - env:
    - name: DATASTORE_TYPE
      value: kubernetes
    - name: WAIT_FOR_DATASTORE
      value: "true"
    - name: NODENAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: CALICO_NETWORKING_BACKEND
      valueFrom:
        configMapKeyRef:
          key: calico_backend
          name: calico-config
    - name: CLUSTER_TYPE
      value: k8s,bgp
    - name: IP
      value: autodetect
    - name: CALICO_IPV4POOL_IPIP
      value: Always
    - name: FELIX_IPINIPMTU
      valueFrom:
        configMapKeyRef:
          key: veth_mtu
          name: calico-config
    - name: CALICO_IPV4POOL_CIDR
      value: 10.244.2.0/24
    - name: CALICO_DISABLE_FILE_LOGGING
      value: "true"
    - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
      value: ACCEPT
    - name: FELIX_IPV6SUPPORT
      value: "false"
    - name: FELIX_LOGSEVERITYSCREEN
      value: info
    - name: FELIX_HEALTHENABLED
      value: "true"
    image: calico/node:v3.8.4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 6
      httpGet:
        host: localhost
        path: /liveness
        port: 9099
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: calico-node
    readinessProbe:
      exec:
        command:
        - /bin/calico-node
        - -bird-ready
        - -felix-ready
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 250m
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
    - mountPath: /run/xtables.lock
      name: xtables-lock
    - mountPath: /var/run/calico
      name: var-run-calico
    - mountPath: /var/lib/calico
      name: var-lib-calico
    - mountPath: /var/run/nodeagent
      name: policysync
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: calico-node-token-92j7v
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  initContainers:
  - command:
    - /opt/cni/bin/calico-ipam
    - -upgrade
    env:
    - name: KUBERNETES_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: CALICO_NETWORKING_BACKEND
      valueFrom:
        configMapKeyRef:
          key: calico_backend
          name: calico-config
    image: calico/cni:v3.8.4
    imagePullPolicy: IfNotPresent
    name: upgrade-ipam
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/cni/networks
      name: host-local-net-dir
    - mountPath: /host/opt/cni/bin
      name: cni-bin-dir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: calico-node-token-92j7v
      readOnly: true
  - command:
    - /install-cni.sh
    env:
    - name: CNI_CONF_NAME
      value: 10-calico.conflist
    - name: CNI_NETWORK_CONFIG
      valueFrom:
        configMapKeyRef:
          key: cni_network_config
          name: calico-config
    - name: KUBERNETES_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: CNI_MTU
      valueFrom:
        configMapKeyRef:
          key: veth_mtu
          name: calico-config
    - name: SLEEP
      value: "false"
    image: calico/cni:v3.8.4
    imagePullPolicy: IfNotPresent
    name: install-cni
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host/opt/cni/bin
      name: cni-bin-dir
    - mountPath: /host/etc/cni/net.d
      name: cni-net-dir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: calico-node-token-92j7v
      readOnly: true
  - image: calico/pod2daemon-flexvol:v3.8.4
    imagePullPolicy: IfNotPresent
    name: flexvol-driver
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host/driver
      name: flexvol-driver-host
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: calico-node-token-92j7v
      readOnly: true
  nodeName: master01
  nodeSelector:
    beta.kubernetes.io/os: linux
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: calico-node
  serviceAccountName: calico-node
  terminationGracePeriodSeconds: 0
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - hostPath:
      path: /lib/modules
      type: ""
    name: lib-modules
  - hostPath:
      path: /var/run/calico
      type: ""
    name: var-run-calico
  - hostPath:
      path: /var/lib/calico
      type: ""
    name: var-lib-calico
  - hostPath:
      path: /run/xtables.lock
      type: FileOrCreate
    name: xtables-lock
  - hostPath:
      path: /opt/cni/bin
      type: ""
    name: cni-bin-dir
  - hostPath:
      path: /etc/cni/net.d
      type: ""
    name: cni-net-dir
  - hostPath:
      path: /var/lib/cni/networks
      type: ""
    name: host-local-net-dir
  - hostPath:
      path: /var/run/nodeagent
      type: DirectoryOrCreate
    name: policysync
  - hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
      type: DirectoryOrCreate
    name: flexvol-driver-host
  - name: calico-node-token-92j7v
    secret:
      defaultMode: 420
      secretName: calico-node-token-92j7v
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-07-23T09:16:48Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-07-23T09:17:28Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-07-23T09:17:28Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-07-23T09:16:07Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://9f89efcb581f371563c8e4eafdd636932ff33328c19530ba351b9ea35a038786
    image: calico/node:v3.8.4
    imageID: docker-pullable://calico/node@sha256:ae2a196f15724fe994e41d8992ed01ad7df871eb5529d55e4e7c55ab0d7ef791
    lastState: {}
    name: calico-node
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-07-23T09:17:15Z"
  hostIP: 192.168.5.12
  initContainerStatuses:
  - containerID: docker://b4502639ba05f9c76755c7f4d83d07062f0f3e50a3beeb1fca6f02d71962c91f
    image: calico/cni:v3.8.4
    imageID: docker-pullable://calico/cni@sha256:040aafdeef49322a1d79f2ec438852af00df7c04d4354fec1acf3e41abb17d12
    lastState: {}
    name: upgrade-ipam
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://b4502639ba05f9c76755c7f4d83d07062f0f3e50a3beeb1fca6f02d71962c91f
        exitCode: 0
        finishedAt: "2020-07-23T09:16:31Z"
        reason: Completed
        startedAt: "2020-07-23T09:16:31Z"
  - containerID: docker://56f066c9e3b7225e1781be016b5fa021bd7f17fac39dcd8f6e860b9c7ab3a6a3
    image: calico/cni:v3.8.4
    imageID: docker-pullable://calico/cni@sha256:040aafdeef49322a1d79f2ec438852af00df7c04d4354fec1acf3e41abb17d12
    lastState: {}
    name: install-cni
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://56f066c9e3b7225e1781be016b5fa021bd7f17fac39dcd8f6e860b9c7ab3a6a3
        exitCode: 0
        finishedAt: "2020-07-23T09:16:34Z"
        reason: Completed
        startedAt: "2020-07-23T09:16:34Z"
  - containerID: docker://f23cef7fcc6d91e2d2ae5385cc0dea43185737733aabdbd6af07ccd7194e3124
    image: calico/pod2daemon-flexvol:v3.8.4
    imageID: docker-pullable://calico/pod2daemon-flexvol@sha256:6dd45f10b54e5d3c9c226504460b12ff3d2a232754c0aa86e8f02d92cf673d94
    lastState: {}
    name: flexvol-driver
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://f23cef7fcc6d91e2d2ae5385cc0dea43185737733aabdbd6af07ccd7194e3124
        exitCode: 0
        finishedAt: "2020-07-23T09:16:46Z"
        reason: Completed
        startedAt: "2020-07-23T09:16:46Z"
  phase: Running
  podIP: 192.168.5.12
  podIPs:
  - ip: 192.168.5.12
  qosClass: Burstable
  startTime: "2020-07-23T09:16:08Z"
